app = "magically-runtime"
primary_region = "bom"

[build]

[deploy]
  release_command = "node packages/runtime/dist/migrate.js"

[env]
  PORT = "4321"
  NODE_ENV = "production"

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
