/**
 * Dummy data for the gallery UI. Replace with API calls when backend is ready.
 */
import type { AgentCardData } from './AgentCard';

export const myAgents: AgentCardData[] = [
  {
    id: 'instagram-poster',
    name: 'Instagram Auto-Poster',
    description: 'Generates carousel content, writes captions, and posts to Instagram on a schedule.',
    icon: '📸',
    color: '#E1306C',
    coverImage: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&h=300&fit=crop',
    category: 'Social Media',
    version: '1.2.0',
    status: 'installed',
    functions: ['generateCarousel', 'writeCaption', 'postToInstagram'],
  },
  {
    id: 'daily-standup',
    name: 'Daily Standup',
    description: 'Summarizes yesterday\'s work, today\'s plan, and blockers from your GitHub + Linear.',
    icon: '📋',
    color: '#3B82F6',
    status: 'draft',
    category: 'Productivity',
    functions: ['summarize'],
  },
  {
    id: 'grocery-list',
    name: 'Grocery List',
    description: 'Manages your grocery list. Add items by voice, organize by aisle, share with family.',
    icon: '🛒',
    color: '#22C55E',
    coverImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
    category: 'Lifestyle',
    version: '1.0.0',
    status: 'installed',
    functions: ['addItem', 'getList', 'shareList'],
  },
  {
    id: 'email-digest',
    name: 'Email Digest',
    description: 'Reads your inbox, categorizes emails, and sends you a daily summary.',
    icon: '📧',
    status: 'draft',
    category: 'Productivity',
  },
];

export const exploreAgents: AgentCardData[] = [
  {
    id: 'podcast-notes',
    name: 'Podcast Notes',
    description: 'Listens to podcasts, extracts key insights, and creates structured notes with timestamps.',
    icon: '🎧',
    color: '#8B5CF6',
    coverImage: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400&h=300&fit=crop',
    author: 'Magically',
    category: 'Media',
    version: '2.1.0',
    status: 'published',
    rating: 4.8,
    installs: 12400,
  },
  {
    id: 'code-reviewer',
    name: 'Code Reviewer',
    description: 'Reviews pull requests for bugs, performance issues, and style violations. Supports 15+ languages.',
    icon: '🔍',
    color: '#06B6D4',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=300&fit=crop',
    author: 'DevTools Co',
    category: 'Developer Tools',
    version: '3.0.0',
    status: 'published',
    rating: 4.9,
    installs: 34200,
  },
  {
    id: 'meeting-prep',
    name: 'Meeting Prep',
    description: 'Researches attendees, summarizes past conversations, and generates talking points.',
    icon: '🤝',
    color: '#F59E0B',
    coverImage: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=400&h=300&fit=crop',
    author: 'Productivity Labs',
    category: 'Productivity',
    version: '1.5.0',
    status: 'published',
    rating: 4.6,
    installs: 8700,
  },
  {
    id: 'fitness-tracker',
    name: 'Fitness Coach',
    description: 'Tracks workouts, suggests routines, and adapts based on your progress and goals.',
    icon: '💪',
    color: '#EF4444',
    coverImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
    author: 'HealthAI',
    category: 'Health & Fitness',
    version: '2.0.0',
    status: 'published',
    rating: 4.7,
    installs: 21300,
  },
  {
    id: 'recipe-finder',
    name: 'Recipe Finder',
    description: 'Takes a photo of your fridge contents and suggests recipes you can make right now.',
    icon: '👨‍🍳',
    color: '#10B981',
    coverImage: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400&h=300&fit=crop',
    author: 'FoodTech',
    category: 'Lifestyle',
    version: '1.3.0',
    status: 'published',
    rating: 4.5,
    installs: 15800,
  },
  {
    id: 'travel-planner',
    name: 'Travel Planner',
    description: 'Plans trips end-to-end: flights, hotels, itineraries, local tips, and budget tracking.',
    icon: '✈️',
    color: '#6366F1',
    coverImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=300&fit=crop',
    author: 'Wanderlust AI',
    category: 'Travel',
    version: '2.2.0',
    status: 'published',
    rating: 4.9,
    installs: 42100,
  },
  {
    id: 'stock-watcher',
    name: 'Stock Watcher',
    description: 'Monitors your portfolio, alerts on price movements, and summarizes market news.',
    icon: '📈',
    color: '#14B8A6',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=300&fit=crop',
    author: 'FinanceAI',
    category: 'Finance',
    version: '1.8.0',
    status: 'published',
    rating: 4.4,
    installs: 19500,
  },
  {
    id: 'language-tutor',
    name: 'Language Tutor',
    description: 'Personalized language learning with conversation practice, grammar correction, and vocabulary tracking.',
    icon: '🗣️',
    color: '#EC4899',
    coverImage: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&h=300&fit=crop',
    author: 'EduTech',
    category: 'Education',
    version: '3.1.0',
    status: 'published',
    rating: 4.8,
    installs: 28900,
  },
];

export const categories = [
  'All',
  'Productivity',
  'Developer Tools',
  'Social Media',
  'Lifestyle',
  'Health & Fitness',
  'Finance',
  'Education',
  'Travel',
  'Media',
];

export const featuredCategory = {
  title: 'Agents that work while you sleep',
  subtitle: 'Featured Collection',
  gradient: 'from-orange-600/30 via-amber-800/20 to-bg-shell',
};
