export type AgentStatus = 'draft' | 'installed' | 'published';

export interface GalleryAgent {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  icon: string;
  color: string;
  gradient: string;
  author: string;
  category: string;
  version: string;
  status: AgentStatus;
  rating?: number;
  ratingCount?: number;
  installs?: number;
  size?: string;
  features?: string[];
  functions?: string[];
  lastUpdated?: string;
}

// 4-6 agents the user is building/has installed
export const myAgents: GalleryAgent[] = [
  {
    id: 'inbox-zero-engine',
    name: 'Inbox Zero Engine',
    subtitle: 'Silence the noise forever',
    description:
      'Autonomously routes newsletters, groups receipts into expense widgets, and drafts replies to important emails — all running silently in the background.',
    icon: '📬',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-violet-700',
    author: 'You',
    category: 'Productivity',
    version: '0.3.0',
    status: 'draft',
    features: ['Email routing', 'Receipt grouping', 'Smart drafts', 'Priority detection'],
    functions: ['routeEmail', 'groupReceipts', 'draftReply', 'classifyPriority'],
    lastUpdated: '2026-03-27',
  },
  {
    id: 'my-portfolio-tracker',
    name: 'Portfolio Pulse',
    subtitle: 'Your wealth at a glance',
    description:
      'Tracks your investment portfolio across brokerages and surfaces a live widget with daily P&L, alerts on unusual moves, and rebalancing suggestions.',
    icon: '📈',
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-700',
    author: 'You',
    category: 'Finance',
    version: '0.1.2',
    status: 'draft',
    features: ['Multi-brokerage sync', 'Live P&L', 'Rebalance alerts'],
    functions: ['syncPortfolio', 'calculatePnL', 'suggestRebalance'],
    lastUpdated: '2026-03-26',
  },
  {
    id: 'content-courier',
    name: 'Content Courier',
    subtitle: 'Your daily media briefing',
    description:
      'Watches your favorite YouTubers, substacks, and podcasts, then distills exactly the 15 minutes of content you care about into a dynamic daily newspaper widget.',
    icon: '📰',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-700',
    author: 'Streamline Labs',
    category: 'Media',
    version: '2.1.0',
    status: 'installed',
    rating: 4.7,
    ratingCount: 1823,
    installs: 94200,
    size: '18 MB',
    features: ['YouTube digest', 'Podcast summaries', 'Substack curation', 'Daily briefing widget'],
    functions: ['fetchFeeds', 'distillContent', 'buildBriefing', 'renderNewspaper'],
    lastUpdated: '2026-03-20',
  },
  {
    id: 'sentient-crm',
    name: 'Sentient CRM',
    subtitle: 'Never forget the people you love',
    description:
      'Monitors your messages and contacts to surface relationship reminders — birthdays, long silences, and thoughtful follow-ups — with one-tap actions.',
    icon: '💛',
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-700',
    author: 'Heartware Inc.',
    category: 'Communication',
    version: '1.4.1',
    status: 'installed',
    rating: 4.8,
    ratingCount: 3412,
    installs: 187000,
    size: '12 MB',
    features: ['Birthday reminders', 'Silence detection', 'Gift suggestions', 'One-tap actions'],
    functions: ['analyzeContacts', 'detectSilence', 'suggestAction', 'sendReminder'],
    lastUpdated: '2026-03-18',
  },
  {
    id: 'shadow-mentor',
    name: 'Shadow Mentor',
    subtitle: 'Rewire your scroll habit',
    description:
      'Intercepts doomscrolling sessions and injects short, visually stunning micro-lessons on topics you actually want to learn. Uses the same addictive patterns for good.',
    icon: '🧠',
    color: '#8b5cf6',
    gradient: 'from-violet-600 to-purple-800',
    author: 'Neuroplastic Co.',
    category: 'Education',
    version: '1.0.3',
    status: 'installed',
    rating: 4.6,
    ratingCount: 2105,
    installs: 112000,
    size: '24 MB',
    features: ['Scroll interception', 'Micro-lessons', 'Visual styles', 'Progress tracking'],
    functions: ['interceptScroll', 'generateLesson', 'trackProgress', 'adaptDifficulty'],
    lastUpdated: '2026-03-22',
  },
  {
    id: 'trip-orchestrator',
    name: 'Trip Orchestrator',
    subtitle: 'Travel runs itself',
    description:
      'Forward a flight confirmation and this agent books your Uber, checks destination weather, pulls restaurant recs, and texts your host — fully autonomous trip management.',
    icon: '✈️',
    color: '#0ea5e9',
    gradient: 'from-sky-500 to-cyan-700',
    author: 'Wanderlust AI',
    category: 'Travel',
    version: '3.2.0',
    status: 'installed',
    rating: 4.9,
    ratingCount: 5201,
    installs: 310000,
    size: '20 MB',
    features: ['Auto ride booking', 'Weather integration', 'Restaurant recs', 'Host messaging', 'Itinerary widget'],
    functions: ['parseConfirmation', 'bookTransport', 'fetchWeather', 'findRestaurants', 'messageHost'],
    lastUpdated: '2026-03-15',
  },
];

// 44 agents in the explore store
export const exploreAgents: GalleryAgent[] = [
  {
    id: 'financial-guardian',
    name: 'Financial Guardian',
    subtitle: 'Stop wasting money silently',
    description:
      'Monitors your bank accounts for unused subscriptions, cancels them via browser automation, and moves savings into high-yield accounts automatically.',
    icon: '🛡️',
    color: '#059669',
    gradient: 'from-emerald-600 to-green-800',
    author: 'VaultMind',
    category: 'Finance',
    version: '2.5.1',
    status: 'published',
    rating: 4.8,
    ratingCount: 7890,
    installs: 423000,
    size: '15 MB',
    features: ['Subscription detection', 'Auto-cancel', 'Savings optimizer', 'Spending alerts'],
    functions: ['scanSubscriptions', 'cancelSubscription', 'moveSavings', 'alertSpending'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'infinite-tutor',
    name: 'Infinite Tutor',
    subtitle: 'Personalized learning every day',
    description:
      'Presents a daily interactive 5-minute mini-game tailored to your exact learning gaps. It remembers what you struggled with yesterday and adapts today.',
    icon: '🎓',
    color: '#7c3aed',
    gradient: 'from-purple-600 to-indigo-800',
    author: 'EduForge',
    category: 'Education',
    version: '3.0.2',
    status: 'published',
    rating: 4.9,
    ratingCount: 12400,
    installs: 498000,
    size: '32 MB',
    features: ['Adaptive difficulty', 'Daily mini-games', 'Progress tracking', 'Multi-subject'],
    functions: ['assessGaps', 'generateGame', 'trackMastery', 'adaptCurriculum'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'argus-deepfake-shield',
    name: 'Argus Shield',
    subtitle: 'Real-time deepfake detection',
    description:
      'Silently analyzes incoming calls and voice messages for AI-generated audio artifacts. Flashes a red alert mid-call when it detects a voice clone.',
    icon: '🔴',
    color: '#dc2626',
    gradient: 'from-red-600 to-rose-800',
    author: 'TruthNet Security',
    category: 'Security',
    version: '1.8.0',
    status: 'published',
    rating: 4.7,
    ratingCount: 4560,
    installs: 267000,
    size: '28 MB',
    features: ['Real-time analysis', 'Voice clone detection', 'Call screening', 'Threat logging'],
    functions: ['analyzeAudio', 'detectDeepfake', 'alertUser', 'logThreat'],
    lastUpdated: '2026-03-21',
  },
  {
    id: 'never-ending-rpg',
    name: 'Infinite Quest',
    subtitle: 'A world shaped by your life',
    description:
      'A persistent RPG where the world, NPCs, and quests are generated daily based on your location, weather, and real-world news. Make 3 decisions each day.',
    icon: '⚔️',
    color: '#b45309',
    gradient: 'from-amber-700 to-yellow-900',
    author: 'Mythforge Studios',
    category: 'Gaming',
    version: '2.3.1',
    status: 'published',
    rating: 4.6,
    ratingCount: 8930,
    installs: 356000,
    size: '45 MB',
    features: ['Dynamic world gen', 'Weather-linked events', 'Persistent characters', 'Daily quests'],
    functions: ['generateWorld', 'processDecision', 'evolveNPCs', 'syncRealWorld'],
    lastUpdated: '2026-03-23',
  },
  {
    id: 'second-brain-architect',
    name: 'Second Brain',
    subtitle: 'Capture everything, forget nothing',
    description:
      'Highlight text, take voice memos, or screenshot anything — the agent categorizes, links, and builds a personalized searchable knowledge wiki automatically.',
    icon: '🧩',
    color: '#6d28d9',
    gradient: 'from-violet-700 to-fuchsia-900',
    author: 'Cortex Labs',
    category: 'Productivity',
    version: '4.1.0',
    status: 'published',
    rating: 4.8,
    ratingCount: 6720,
    installs: 389000,
    size: '22 MB',
    features: ['Auto-categorization', 'Knowledge linking', 'Voice capture', 'Searchable wiki'],
    functions: ['captureInput', 'categorize', 'linkKnowledge', 'searchWiki'],
    lastUpdated: '2026-03-19',
  },
  {
    id: 'personalized-podcast',
    name: 'Daily Cast',
    subtitle: 'A podcast made just for you',
    description:
      'Synthesizes your reading list, interests, and daily news into a 20-minute audio show with two AI hosts discussing exactly the topics you care about.',
    icon: '🎙️',
    color: '#e11d48',
    gradient: 'from-rose-600 to-pink-800',
    author: 'Wavelength Audio',
    category: 'Media',
    version: '1.9.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 3890,
    installs: 201000,
    size: '35 MB',
    features: ['Dual AI hosts', 'Interest-based topics', 'Daily generation', 'Offline playback'],
    functions: ['aggregateInterests', 'generateScript', 'synthesizeAudio', 'publishEpisode'],
    lastUpdated: '2026-03-22',
  },
  {
    id: 'health-dashboard',
    name: 'Vitals Hub',
    subtitle: 'Your body, one glance',
    description:
      'Connects Apple Health, your grocery list, and sleep tracker to deliver actionable daily recommendations — from rescheduling workouts to ordering supplements.',
    icon: '💚',
    color: '#16a34a',
    gradient: 'from-green-600 to-emerald-800',
    author: 'BodyGraph AI',
    category: 'Health & Fitness',
    version: '2.7.3',
    status: 'published',
    rating: 4.7,
    ratingCount: 5430,
    installs: 312000,
    size: '19 MB',
    features: ['Health sync', 'Sleep analysis', 'Workout rescheduling', 'Nutrition tips'],
    functions: ['syncHealthData', 'analyzeSleep', 'rescheduleWorkout', 'suggestNutrition'],
    lastUpdated: '2026-03-20',
  },
  {
    id: 'butterfly-effect',
    name: 'Butterfly Effect',
    subtitle: 'Your life powers a world',
    description:
      'A tamagotchi-style sim where your real step count, calendar stress, weather, and music habits shape a living town widget. Sleep well and crops grow; bad meetings cause volcanoes.',
    icon: '🦋',
    color: '#d946ef',
    gradient: 'from-fuchsia-500 to-purple-700',
    author: 'Mythforge Studios',
    category: 'Gaming',
    version: '1.2.0',
    status: 'published',
    rating: 4.4,
    ratingCount: 2340,
    installs: 134000,
    size: '38 MB',
    features: ['Life-data driven', 'Living town sim', 'Weather effects', 'Music mood link'],
    functions: ['ingestLifeData', 'simulateWorld', 'renderTown', 'triggerEvent'],
    lastUpdated: '2026-03-18',
  },
  {
    id: 'mystery-escape-room',
    name: 'Phantom Escape',
    subtitle: 'Puzzles hidden in your OS',
    description:
      'An ARG escape room that hides clues across your real apps — fake calendar events, coded emails, and curated playlists. Solve puzzles by hunting through your own digital life.',
    icon: '🔐',
    color: '#1e293b',
    gradient: 'from-slate-700 to-gray-900',
    author: 'Riddle Collective',
    category: 'Gaming',
    version: '1.0.1',
    status: 'published',
    rating: 4.3,
    ratingCount: 1450,
    installs: 78000,
    size: '16 MB',
    features: ['Cross-app clues', 'Weekly chapters', 'Multiplayer hints', 'Leaderboard'],
    functions: ['plantClue', 'validateSolution', 'generatePuzzle', 'progressChapter'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'proactive-job-hunter',
    name: 'Job Radar',
    subtitle: 'Your silent career agent',
    description:
      'Set your dream role parameters once. It monitors job boards, company pages, and LinkedIn daily, drafts tailored cover letters, and applies on your behalf.',
    icon: '🎯',
    color: '#0284c7',
    gradient: 'from-sky-600 to-blue-800',
    author: 'CareerPilot',
    category: 'Productivity',
    version: '2.0.4',
    status: 'published',
    rating: 4.6,
    ratingCount: 4120,
    installs: 245000,
    size: '14 MB',
    features: ['Board monitoring', 'Auto-apply', 'Cover letter gen', 'Weekly digest'],
    functions: ['scanJobs', 'matchCriteria', 'draftCoverLetter', 'submitApplication'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'code-game-forge',
    name: 'Code Forge',
    subtitle: 'Describe a game, play it now',
    description:
      'Tell the agent what game you want — it codes a fully playable HTML5 game in the background using a container and surfaces it as a widget within minutes.',
    icon: '🕹️',
    color: '#4f46e5',
    gradient: 'from-indigo-600 to-blue-800',
    author: 'PixelSmith AI',
    category: 'Gaming',
    version: '1.5.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 6780,
    installs: 287000,
    size: '42 MB',
    features: ['Natural language input', 'HTML5 games', 'Theme customization', 'Shareable games'],
    functions: ['parseGameRequest', 'generateCode', 'testGame', 'deployWidget'],
    lastUpdated: '2026-03-26',
  },
  {
    id: 'hallucination-network',
    name: 'Dream Stream',
    subtitle: 'Shows that only you will see',
    description:
      'Generates a bespoke 10-minute animated episode every night based on your reading, tweets, and trending news. Watch once and it vanishes forever.',
    icon: '🌀',
    color: '#a21caf',
    gradient: 'from-purple-700 to-fuchsia-900',
    author: 'Ephemera Media',
    category: 'Media',
    version: '0.9.1',
    status: 'published',
    rating: 4.2,
    ratingCount: 1890,
    installs: 89000,
    size: '50 MB',
    features: ['Nightly generation', 'Personalized plots', 'Ephemeral viewing', 'Visual styles'],
    functions: ['analyzeInterests', 'generateScript', 'renderAnimation', 'scheduleRelease'],
    lastUpdated: '2026-03-17',
  },
  {
    id: 'smart-home-conductor',
    name: 'Home Mind',
    subtitle: 'Your house anticipates you',
    description:
      'Learns your daily routines and orchestrates smart home devices proactively — lights dim before bedtime, coffee starts before your alarm, blinds open with sunrise.',
    icon: '🏠',
    color: '#ca8a04',
    gradient: 'from-yellow-600 to-amber-800',
    author: 'NestIQ',
    category: 'Home',
    version: '3.4.2',
    status: 'published',
    rating: 4.7,
    ratingCount: 3210,
    installs: 198000,
    size: '11 MB',
    features: ['Routine learning', 'Multi-device control', 'Energy saving', 'Scene automation'],
    functions: ['learnRoutine', 'orchestrateDevices', 'optimizeEnergy', 'triggerScene'],
    lastUpdated: '2026-03-21',
  },
  {
    id: 'social-media-autopilot',
    name: 'Social Pilot',
    subtitle: 'Grow while you sleep',
    description:
      'Analyzes your best-performing content, generates optimized posts for each platform, schedules them at peak engagement times, and responds to comments intelligently.',
    icon: '📱',
    color: '#2563eb',
    gradient: 'from-blue-600 to-indigo-800',
    author: 'ViralStack',
    category: 'Social Media',
    version: '4.2.1',
    status: 'published',
    rating: 4.5,
    ratingCount: 9870,
    installs: 467000,
    size: '17 MB',
    features: ['Cross-platform posting', 'Engagement analytics', 'Auto-scheduling', 'Comment replies'],
    functions: ['analyzeContent', 'generatePost', 'schedulePost', 'replyToComments'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'git-guardian',
    name: 'Git Guardian',
    subtitle: 'Never merge a bad PR again',
    description:
      'Reviews every pull request in your repos, catches security vulnerabilities and logic errors, suggests improvements, and auto-approves safe dependency bumps.',
    icon: '🔍',
    color: '#475569',
    gradient: 'from-slate-600 to-zinc-800',
    author: 'DevShield',
    category: 'Developer Tools',
    version: '5.1.0',
    status: 'published',
    rating: 4.8,
    ratingCount: 11200,
    installs: 489000,
    size: '13 MB',
    features: ['PR review', 'Vulnerability scan', 'Auto-approve deps', 'Style enforcement'],
    functions: ['reviewPR', 'scanVulnerabilities', 'autoApproveDeps', 'enforceStyle'],
    lastUpdated: '2026-03-26',
  },
  {
    id: 'deploy-sentinel',
    name: 'Deploy Sentinel',
    subtitle: 'Ship with zero anxiety',
    description:
      'Monitors your CI/CD pipelines, auto-rolls back failed deployments, surfaces error logs in a clean widget, and notifies your team on Slack with root cause analysis.',
    icon: '🚀',
    color: '#0891b2',
    gradient: 'from-cyan-600 to-teal-800',
    author: 'LaunchPad AI',
    category: 'Developer Tools',
    version: '2.8.0',
    status: 'published',
    rating: 4.7,
    ratingCount: 5670,
    installs: 312000,
    size: '16 MB',
    features: ['Pipeline monitoring', 'Auto-rollback', 'Root cause analysis', 'Slack integration'],
    functions: ['monitorPipeline', 'rollbackDeploy', 'analyzeFailure', 'notifyTeam'],
    lastUpdated: '2026-03-23',
  },
  {
    id: 'meal-planner-pro',
    name: 'Meal Maestro',
    subtitle: 'Eat well without thinking',
    description:
      'Plans your weekly meals based on dietary goals, fridge contents, and local grocery deals. Generates shopping lists and can auto-order delivery for missing ingredients.',
    icon: '🍽️',
    color: '#ea580c',
    gradient: 'from-orange-600 to-red-800',
    author: 'NourishAI',
    category: 'Health & Fitness',
    version: '2.3.1',
    status: 'published',
    rating: 4.6,
    ratingCount: 4560,
    installs: 234000,
    size: '21 MB',
    features: ['Diet tracking', 'Recipe generation', 'Grocery deals', 'Auto-ordering'],
    functions: ['planMeals', 'generateRecipe', 'buildShoppingList', 'orderGroceries'],
    lastUpdated: '2026-03-19',
  },
  {
    id: 'focus-fortress',
    name: 'Focus Fortress',
    subtitle: 'Deep work on autopilot',
    description:
      'Blocks distracting apps and websites during focus sessions, silences non-urgent notifications, and tracks your deep work streaks with a beautiful progress widget.',
    icon: '🏰',
    color: '#7e22ce',
    gradient: 'from-purple-700 to-violet-900',
    author: 'Zenith Productivity',
    category: 'Productivity',
    version: '3.1.0',
    status: 'published',
    rating: 4.7,
    ratingCount: 6340,
    installs: 345000,
    size: '8 MB',
    features: ['App blocking', 'Notification silencing', 'Streak tracking', 'Focus analytics'],
    functions: ['startSession', 'blockDistractions', 'trackStreak', 'generateReport'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'wardrobe-ai',
    name: 'Outfit Oracle',
    subtitle: 'Styled by your closet, daily',
    description:
      'Photograph your wardrobe once and get daily outfit suggestions based on weather, your calendar, and what you have not worn recently. Reduces decision fatigue to zero.',
    icon: '👔',
    color: '#be185d',
    gradient: 'from-pink-700 to-rose-900',
    author: 'ThreadLogic',
    category: 'Lifestyle',
    version: '1.7.2',
    status: 'published',
    rating: 4.4,
    ratingCount: 2890,
    installs: 156000,
    size: '26 MB',
    features: ['Wardrobe scanning', 'Weather matching', 'Calendar awareness', 'Wear rotation'],
    functions: ['scanWardrobe', 'matchWeather', 'suggestOutfit', 'trackWornItems'],
    lastUpdated: '2026-03-22',
  },
  {
    id: 'api-docs-genie',
    name: 'Docs Genie',
    subtitle: 'API docs that write themselves',
    description:
      'Watches your codebase for API changes, generates OpenAPI specs, updates documentation sites, and alerts the team when endpoints are modified.',
    icon: '📖',
    color: '#0d9488',
    gradient: 'from-teal-600 to-cyan-800',
    author: 'Docuflow',
    category: 'Developer Tools',
    version: '2.4.0',
    status: 'published',
    rating: 4.6,
    ratingCount: 3450,
    installs: 198000,
    size: '10 MB',
    features: ['Auto-generation', 'OpenAPI sync', 'Change alerts', 'Version diffing'],
    functions: ['watchCodebase', 'generateSpec', 'updateDocs', 'alertChanges'],
    lastUpdated: '2026-03-20',
  },
  {
    id: 'expense-splitter',
    name: 'Split Smart',
    subtitle: 'Group expenses made painless',
    description:
      'Photograph receipts and the agent extracts items, assigns them to group members, calculates splits including tax and tip, and sends payment requests automatically.',
    icon: '🧾',
    color: '#65a30d',
    gradient: 'from-lime-600 to-green-800',
    author: 'FairShare AI',
    category: 'Finance',
    version: '1.6.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 3120,
    installs: 189000,
    size: '12 MB',
    features: ['Receipt scanning', 'Smart splitting', 'Tax calculation', 'Payment requests'],
    functions: ['scanReceipt', 'assignItems', 'calculateSplit', 'requestPayment'],
    lastUpdated: '2026-03-23',
  },
  {
    id: 'writing-coach',
    name: 'Prose Engine',
    subtitle: 'Your relentless writing partner',
    description:
      'Provides real-time feedback on clarity, tone, and structure as you write. Tracks your daily word count, highlights crutch words, and suggests stronger alternatives.',
    icon: '✍️',
    color: '#9333ea',
    gradient: 'from-purple-600 to-pink-800',
    author: 'Inkwell AI',
    category: 'Writing',
    version: '3.0.1',
    status: 'published',
    rating: 4.7,
    ratingCount: 5670,
    installs: 298000,
    size: '18 MB',
    features: ['Real-time feedback', 'Tone analysis', 'Word count tracker', 'Crutch word alerts'],
    functions: ['analyzeText', 'suggestAlternatives', 'trackWordCount', 'evaluateTone'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'research-rabbit',
    name: 'Research Rabbit',
    subtitle: 'Academic papers on autopilot',
    description:
      'Feed it a research question and it crawls arXiv, PubMed, and Google Scholar daily, summarizes new papers, and builds a living literature review widget.',
    icon: '🐇',
    color: '#dc2626',
    gradient: 'from-red-500 to-orange-700',
    author: 'ScholarMind',
    category: 'Research',
    version: '2.1.3',
    status: 'published',
    rating: 4.8,
    ratingCount: 4230,
    installs: 267000,
    size: '15 MB',
    features: ['Multi-source crawling', 'Paper summaries', 'Citation graphs', 'Literature review'],
    functions: ['crawlSources', 'summarizePaper', 'buildCitationGraph', 'updateReview'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'price-hawk',
    name: 'Price Hawk',
    subtitle: 'Never overpay for anything',
    description:
      'Monitors prices on your wishlisted items across Amazon, eBay, and other retailers. Alerts you at the optimal buy moment and can auto-purchase when price drops below your target.',
    icon: '🦅',
    color: '#b91c1c',
    gradient: 'from-red-700 to-amber-900',
    author: 'BargainBot',
    category: 'Shopping',
    version: '2.9.0',
    status: 'published',
    rating: 4.6,
    ratingCount: 7890,
    installs: 412000,
    size: '9 MB',
    features: ['Price tracking', 'Multi-retailer', 'Drop alerts', 'Auto-purchase'],
    functions: ['trackPrice', 'compareRetailers', 'alertDrop', 'executePurchase'],
    lastUpdated: '2026-03-26',
  },
  {
    id: 'sleep-architect',
    name: 'Sleep Architect',
    subtitle: 'Engineer your perfect night',
    description:
      'Analyzes your sleep patterns, adjusts smart home lighting and temperature before bed, suggests wind-down routines, and generates personalized sleep soundscapes.',
    icon: '😴',
    color: '#312e81',
    gradient: 'from-indigo-900 to-blue-950',
    author: 'RestWell Labs',
    category: 'Health & Fitness',
    version: '1.4.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 2560,
    installs: 145000,
    size: '20 MB',
    features: ['Sleep analysis', 'Smart home control', 'Wind-down routines', 'Soundscapes'],
    functions: ['analyzeSleep', 'adjustEnvironment', 'suggestRoutine', 'generateSoundscape'],
    lastUpdated: '2026-03-18',
  },
  {
    id: 'language-immersion',
    name: 'Babel Agent',
    subtitle: 'Learn languages by living them',
    description:
      'Gradually replaces words in your notifications and UI with your target language. Starts with common words and escalates. Full immersion without leaving home.',
    icon: '🌍',
    color: '#0369a1',
    gradient: 'from-sky-700 to-blue-900',
    author: 'PolyglotAI',
    category: 'Education',
    version: '2.2.0',
    status: 'published',
    rating: 4.4,
    ratingCount: 3450,
    installs: 178000,
    size: '23 MB',
    features: ['Gradual immersion', 'Context learning', 'Spaced repetition', 'Pronunciation'],
    functions: ['replaceWords', 'assessLevel', 'scheduleRepetition', 'evaluatePronunciation'],
    lastUpdated: '2026-03-21',
  },
  {
    id: 'meeting-phantom',
    name: 'Meeting Phantom',
    subtitle: 'Be everywhere at once',
    description:
      'Joins your video meetings silently, takes structured notes with action items, summarizes decisions, and sends follow-up messages to attendees — all without you lifting a finger.',
    icon: '👻',
    color: '#4338ca',
    gradient: 'from-indigo-700 to-violet-900',
    author: 'GhostWork AI',
    category: 'Communication',
    version: '3.5.1',
    status: 'published',
    rating: 4.8,
    ratingCount: 8920,
    installs: 456000,
    size: '25 MB',
    features: ['Auto-join meetings', 'Structured notes', 'Action items', 'Follow-up emails'],
    functions: ['joinMeeting', 'transcribe', 'extractActions', 'sendFollowUp'],
    lastUpdated: '2026-03-26',
  },
  {
    id: 'data-pipeline-buddy',
    name: 'Pipeline Buddy',
    subtitle: 'ETL without the headaches',
    description:
      'Describes your data sources in plain English and the agent builds, monitors, and self-heals ETL pipelines. Alerts you only when human judgment is needed.',
    icon: '🔄',
    color: '#0e7490',
    gradient: 'from-cyan-700 to-teal-900',
    author: 'DataFlowHQ',
    category: 'Data',
    version: '2.0.0',
    status: 'published',
    rating: 4.6,
    ratingCount: 2340,
    installs: 134000,
    size: '18 MB',
    features: ['Natural language config', 'Self-healing', 'Schema detection', 'Anomaly alerts'],
    functions: ['buildPipeline', 'monitorHealth', 'healFailure', 'detectAnomaly'],
    lastUpdated: '2026-03-22',
  },
  {
    id: 'password-fortress',
    name: 'Cipher Guard',
    subtitle: 'Passwords managed invisibly',
    description:
      'Generates, rotates, and fills strong passwords across all your accounts. Monitors the dark web for credential leaks and forces rotation when a breach is detected.',
    icon: '🔑',
    color: '#374151',
    gradient: 'from-gray-700 to-slate-900',
    author: 'LockBox Security',
    category: 'Security',
    version: '4.0.2',
    status: 'published',
    rating: 4.9,
    ratingCount: 10500,
    installs: 498000,
    size: '7 MB',
    features: ['Password generation', 'Auto-rotation', 'Breach monitoring', 'Auto-fill'],
    functions: ['generatePassword', 'rotateCredential', 'monitorBreaches', 'autoFill'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'spotify-dj-agent',
    name: 'Mood DJ',
    subtitle: 'Music that reads the room',
    description:
      'Analyzes your calendar, time of day, weather, and heart rate to auto-curate the perfect playlist. Transitions smoothly between focus, commute, and workout modes.',
    icon: '🎵',
    color: '#059669',
    gradient: 'from-emerald-600 to-teal-800',
    author: 'BeatSense',
    category: 'Music',
    version: '2.6.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 5670,
    installs: 334000,
    size: '14 MB',
    features: ['Mood detection', 'Context playlists', 'Smooth transitions', 'Heart rate sync'],
    functions: ['detectMood', 'curatePlaylist', 'transitionMode', 'syncBiometrics'],
    lastUpdated: '2026-03-23',
  },
  {
    id: 'plant-parent',
    name: 'Plant Parent',
    subtitle: 'Every plant thrives now',
    description:
      'Identifies your houseplants from photos, creates custom care schedules, monitors light conditions via your phone sensors, and reminds you to water at the right time.',
    icon: '🌱',
    color: '#15803d',
    gradient: 'from-green-700 to-lime-900',
    author: 'LeafLogic',
    category: 'Home',
    version: '1.8.1',
    status: 'published',
    rating: 4.4,
    ratingCount: 2120,
    installs: 112000,
    size: '16 MB',
    features: ['Plant identification', 'Care schedules', 'Light monitoring', 'Water reminders'],
    functions: ['identifyPlant', 'createSchedule', 'monitorLight', 'remindWater'],
    lastUpdated: '2026-03-19',
  },
  {
    id: 'contract-analyzer',
    name: 'Contract Lens',
    subtitle: 'Read the fine print instantly',
    description:
      'Upload any contract and the agent highlights risky clauses, compares terms against market standards, suggests negotiation points, and tracks renewal dates.',
    icon: '📝',
    color: '#92400e',
    gradient: 'from-amber-800 to-yellow-950',
    author: 'LegalEase AI',
    category: 'Productivity',
    version: '2.1.0',
    status: 'published',
    rating: 4.7,
    ratingCount: 3780,
    installs: 223000,
    size: '13 MB',
    features: ['Risk highlighting', 'Market comparison', 'Negotiation tips', 'Renewal tracking'],
    functions: ['analyzeContract', 'highlightRisks', 'compareBenchmark', 'trackRenewal'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'workout-generator',
    name: 'Iron Coach',
    subtitle: 'Personal trainer in your pocket',
    description:
      'Generates daily workout plans based on your equipment, fitness level, and goals. Tracks progressive overload, adjusts for soreness, and visualizes strength gains.',
    icon: '💪',
    color: '#dc2626',
    gradient: 'from-red-600 to-orange-800',
    author: 'FitForge',
    category: 'Health & Fitness',
    version: '3.2.0',
    status: 'published',
    rating: 4.6,
    ratingCount: 7230,
    installs: 378000,
    size: '19 MB',
    features: ['Custom workouts', 'Progressive overload', 'Soreness tracking', 'Strength charts'],
    functions: ['generateWorkout', 'trackProgress', 'adjustForRecovery', 'visualizeGains'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'travel-budget-optimizer',
    name: 'Nomad Wallet',
    subtitle: 'Travel more, spend less',
    description:
      'Finds the cheapest flight and hotel combinations across flexible dates, monitors price drops, and builds a day-by-day budget plan for your destination.',
    icon: '🗺️',
    color: '#0d9488',
    gradient: 'from-teal-600 to-emerald-800',
    author: 'Wanderlust AI',
    category: 'Travel',
    version: '1.9.2',
    status: 'published',
    rating: 4.5,
    ratingCount: 3450,
    installs: 198000,
    size: '11 MB',
    features: ['Flexible date search', 'Price monitoring', 'Budget planning', 'Currency conversion'],
    functions: ['searchFlights', 'monitorPrices', 'buildBudget', 'convertCurrency'],
    lastUpdated: '2026-03-21',
  },
  {
    id: 'creative-brief-generator',
    name: 'Brief Spark',
    subtitle: 'Briefs that inspire great work',
    description:
      'Describe your project and the agent generates comprehensive creative briefs with mood boards, color palettes, typography suggestions, and competitive analysis.',
    icon: '🎨',
    color: '#e11d48',
    gradient: 'from-rose-600 to-fuchsia-800',
    author: 'Creative Engine',
    category: 'Creative',
    version: '1.3.0',
    status: 'published',
    rating: 4.4,
    ratingCount: 2340,
    installs: 134000,
    size: '22 MB',
    features: ['Mood boards', 'Color palettes', 'Competitive analysis', 'Typography picks'],
    functions: ['generateBrief', 'buildMoodBoard', 'analyzeCompetitors', 'suggestTypography'],
    lastUpdated: '2026-03-18',
  },
  {
    id: 'newsletter-curator',
    name: 'Digest Engine',
    subtitle: 'Newsletters worth reading',
    description:
      'Curates a weekly newsletter from your favorite sources, writes original commentary connecting the dots between articles, and handles subscriber management.',
    icon: '💌',
    color: '#7c3aed',
    gradient: 'from-violet-600 to-indigo-800',
    author: 'PressForge',
    category: 'Writing',
    version: '2.0.1',
    status: 'published',
    rating: 4.5,
    ratingCount: 1890,
    installs: 98000,
    size: '10 MB',
    features: ['Source curation', 'Original commentary', 'Subscriber management', 'A/B testing'],
    functions: ['curateSources', 'writeCommentary', 'manageSubscribers', 'testSubjectLines'],
    lastUpdated: '2026-03-22',
  },
  {
    id: 'instagram-autoposter',
    name: 'Insta Flow',
    subtitle: 'Post perfectly, automatically',
    description:
      'Schedules Instagram posts at peak engagement times, generates captions and hashtags from your photos, and maintains a consistent visual grid aesthetic.',
    icon: '📸',
    color: '#c026d3',
    gradient: 'from-fuchsia-600 to-pink-800',
    author: 'ViralStack',
    category: 'Social Media',
    version: '3.1.0',
    status: 'published',
    rating: 4.4,
    ratingCount: 5430,
    installs: 289000,
    size: '15 MB',
    features: ['Peak-time scheduling', 'Caption generation', 'Hashtag optimization', 'Grid planning'],
    functions: ['analyzeEngagement', 'generateCaption', 'optimizeHashtags', 'planGrid'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'tax-prep-assistant',
    name: 'Tax Pilot',
    subtitle: 'Tax season on autopilot',
    description:
      'Aggregates income sources, categorizes deductible expenses from your accounts, flags missing documents, and pre-fills tax forms for your accountant.',
    icon: '🧮',
    color: '#166534',
    gradient: 'from-green-800 to-emerald-950',
    author: 'VaultMind',
    category: 'Finance',
    version: '1.1.0',
    status: 'published',
    rating: 4.6,
    ratingCount: 3210,
    installs: 178000,
    size: '11 MB',
    features: ['Income aggregation', 'Expense categorization', 'Document tracking', 'Form pre-fill'],
    functions: ['aggregateIncome', 'categorizeExpenses', 'flagMissingDocs', 'prefillForms'],
    lastUpdated: '2026-03-15',
  },
  {
    id: 'habit-weaver',
    name: 'Habit Weaver',
    subtitle: 'Build habits that actually stick',
    description:
      'Uses behavioral science to design micro-habit chains. Nudges you at contextually perfect moments and adapts the difficulty curve based on your adherence patterns.',
    icon: '🔗',
    color: '#0f766e',
    gradient: 'from-teal-700 to-green-900',
    author: 'Neuroplastic Co.',
    category: 'Lifestyle',
    version: '2.4.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 4120,
    installs: 234000,
    size: '9 MB',
    features: ['Micro-habits', 'Smart nudges', 'Adherence tracking', 'Difficulty scaling'],
    functions: ['designHabitChain', 'sendNudge', 'trackAdherence', 'adjustDifficulty'],
    lastUpdated: '2026-03-23',
  },
  {
    id: 'video-clipper',
    name: 'Clip Studio',
    subtitle: 'Viral clips from long videos',
    description:
      'Upload a long video and the agent identifies the most engaging moments, clips them, adds captions and transitions, and exports vertical formats for TikTok and Reels.',
    icon: '🎬',
    color: '#9333ea',
    gradient: 'from-purple-600 to-violet-800',
    author: 'Ephemera Media',
    category: 'Creative',
    version: '2.5.0',
    status: 'published',
    rating: 4.7,
    ratingCount: 6780,
    installs: 356000,
    size: '48 MB',
    features: ['Auto-clipping', 'Caption overlay', 'Vertical export', 'Engagement scoring'],
    functions: ['detectHighlights', 'clipSegment', 'addCaptions', 'exportVertical'],
    lastUpdated: '2026-03-26',
  },
  {
    id: 'zapier-killer',
    name: 'Flow Weaver',
    subtitle: 'Automate anything in English',
    description:
      'Describe a workflow in plain English and the agent builds cross-app automations. Connects 200+ services, handles errors gracefully, and self-heals broken connections.',
    icon: '⚡',
    color: '#eab308',
    gradient: 'from-yellow-500 to-orange-700',
    author: 'AutoPilot Labs',
    category: 'Automation',
    version: '3.8.0',
    status: 'published',
    rating: 4.8,
    ratingCount: 9870,
    installs: 478000,
    size: '14 MB',
    features: ['Natural language config', '200+ integrations', 'Error handling', 'Self-healing'],
    functions: ['parseWorkflow', 'connectServices', 'executeFlow', 'healConnection'],
    lastUpdated: '2026-03-25',
  },
  {
    id: 'music-practice-coach',
    name: 'Tempo Coach',
    subtitle: 'Master any instrument faster',
    description:
      'Listens to your practice sessions via microphone, detects timing and pitch errors, suggests targeted exercises, and tracks your progression over weeks.',
    icon: '🎹',
    color: '#1d4ed8',
    gradient: 'from-blue-700 to-indigo-900',
    author: 'BeatSense',
    category: 'Music',
    version: '1.6.0',
    status: 'published',
    rating: 4.5,
    ratingCount: 2340,
    installs: 123000,
    size: '30 MB',
    features: ['Pitch detection', 'Timing analysis', 'Targeted exercises', 'Progress charts'],
    functions: ['analyzePractice', 'detectErrors', 'suggestExercise', 'trackProgression'],
    lastUpdated: '2026-03-20',
  },
  {
    id: 'schema-migrator',
    name: 'Schema Shift',
    subtitle: 'Database migrations made safe',
    description:
      'Analyzes your database schema changes, generates safe migration scripts with rollback plans, dry-runs against a shadow database, and deploys with zero downtime.',
    icon: '🗄️',
    color: '#0284c7',
    gradient: 'from-sky-700 to-cyan-900',
    author: 'DataFlowHQ',
    category: 'Developer Tools',
    version: '2.3.0',
    status: 'published',
    rating: 4.7,
    ratingCount: 3890,
    installs: 212000,
    size: '12 MB',
    features: ['Safe migrations', 'Rollback plans', 'Shadow testing', 'Zero downtime'],
    functions: ['analyzeSchema', 'generateMigration', 'dryRun', 'deployMigration'],
    lastUpdated: '2026-03-24',
  },
  {
    id: 'gift-finder',
    name: 'Gift Whisperer',
    subtitle: 'Perfect gifts every time',
    description:
      'Analyzes a person based on their social profiles and your past conversations, then suggests thoughtful, personalized gift ideas within your budget across multiple retailers.',
    icon: '🎁',
    color: '#e11d48',
    gradient: 'from-rose-600 to-red-800',
    author: 'Heartware Inc.',
    category: 'Shopping',
    version: '1.4.0',
    status: 'published',
    rating: 4.3,
    ratingCount: 2560,
    installs: 145000,
    size: '10 MB',
    features: ['Profile analysis', 'Budget matching', 'Multi-retailer search', 'Occasion reminders'],
    functions: ['analyzeProfile', 'searchGifts', 'matchBudget', 'remindOccasion'],
    lastUpdated: '2026-03-19',
  },
];

// All unique categories from the agents
export const categories: string[] = [
  'All',
  'Automation',
  'Communication',
  'Creative',
  'Data',
  'Developer Tools',
  'Education',
  'Finance',
  'Gaming',
  'Health & Fitness',
  'Home',
  'Lifestyle',
  'Media',
  'Music',
  'Productivity',
  'Research',
  'Security',
  'Shopping',
  'Social Media',
  'Travel',
  'Writing',
];
